# Generated by Django 3.2.5 on 2021-09-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_auto_20210912_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='full_text',
        ),
    ]
